name: paul
favicon: null
layout_spectrum: 0.15236359206028283
typography_spectrum: 0.7212307942099869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8033596044406295
  lightness: 0.6207481047604233
  saturation: 0.34804519382305443
  rhythmicContrast: 0.058695831801742315
purpose: []
